# Generated by Django 5.1.1 on 2024-09-12 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Код товара')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('age_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст (от)')),
                ('age_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст (до)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Общий вид')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина')),
                ('params', models.TextField(blank=True, default=None, null=True, verbose_name='Дополнительные параметры')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('concrete', models.FloatField(blank=True, null=True, verbose_name='Бетон')),
                ('installation_time', models.FloatField(blank=True, null=True, verbose_name='Время установки')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тэг товара')),
            ],
            options={
                'verbose_name': 'Тэг товара',
                'verbose_name_plural': 'Тэги товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар-категория',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Товар-тег',
            },
        ),
        migrations.CreateModel(
            name='UserTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
