# Generated by Django 5.0.2 on 2024-10-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total_price_alter_order_status_orderelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='Стоимость'),
        ),
    ]
