# Generated by Django 5.0.2 on 2024-10-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderelement_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Подан'), ('2', 'На рассмотрении'), ('3', 'Принят'), ('4', 'Выполняется'), ('5', 'Готов')], default='Подан', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
