# Generated by Django 5.1.4 on 2024-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице или нет (макс: 5 категорий)'),
        ),
    ]
