# Generated by Django 5.1.4 on 2024-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='categories_images', verbose_name='Главное фото категории'),
        ),
    ]
