# Generated by Django 4.2.17 on 2024-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_catimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='image',
            field=models.ImageField(upload_to='cat_images', verbose_name='Картинка'),
        ),
    ]
