# Generated by Django 5.1.5 on 2025-02-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_catimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ready_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Код проекта')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование проекта')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Готовый проект',
                'verbose_name_plural': 'Готовые проекты',
            },
        ),
    ]
