# Generated by Django 5.1.5 on 2025-02-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_ready_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ready_project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products_images', verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='Project_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='products_images', verbose_name='Общий вид')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ready_project')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проекта',
            },
        ),
    ]
