# Generated by Django 5.1.5 on 2025-02-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_ready_project_video_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ready_project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects_videos', verbose_name='Видео'),
        ),
    ]
