# Generated by Django 5.1.5 on 2025-02-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_ready_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ready_project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опиание'),
        ),
    ]
