# Generated by Django 5.1.5 on 2025-02-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_ready_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show_on_home',
        ),
        migrations.DeleteModel(
            name='CatImage',
        ),
    ]
