# Generated by Django 5.1.5 on 2025-02-08 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_category_show_on_home_delete_catimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ready_project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects_videos', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm', 'avi', 'mkv', 'wmv', 'swf'])], verbose_name='Видео'),
        ),
    ]
