# Generated by Django 5.1.5 on 2025-02-09 03:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_ready_project_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculated_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Код проекта')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование проекта')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('file', models.FileField(blank=True, null=True, upload_to='projects_files', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm', 'avi', 'mkv', 'wmv', 'swf'])], verbose_name='Видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опиание')),
            ],
            options={
                'verbose_name': 'Проект с расчетами',
                'verbose_name_plural': 'Проекты с расчетами',
            },
        ),
        migrations.CreateModel(
            name='Calculated_project_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='products_images', verbose_name='Общий вид')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.calculated_project')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проекта',
            },
        ),
    ]
