# Generated by Django 5.1.5 on 2025-02-09 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_calculated_project_calculated_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculated_project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects_files', validators=[django.core.validators.FileExtensionValidator(['txt', 'docx', 'xlsx', 'doc', 'pdf', 'odt', 'tif'])], verbose_name='Видео'),
        ),
    ]
