# Generated by Django 5.1.5 on 2025-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_calculated_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculated_project',
            name='for_tos',
            field=models.BooleanField(blank=True, default=False, verbose_name='Для ТОС или нет'),
        ),
        migrations.AddField(
            model_name='ready_project',
            name='for_tos',
            field=models.BooleanField(blank=True, default=False, verbose_name='Для ТОС или нет'),
        ),
        migrations.AlterField(
            model_name='calculated_project_photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='calculated_projects_images', verbose_name='Общий вид'),
        ),
        migrations.AlterField(
            model_name='project_photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='ready_projects_images', verbose_name='Общий вид'),
        ),
    ]
